const ORACLE_SQL = {
  vendasDiaVendedor: `
    SELECT
      C.CODUSUR,
      MAX(U.NOME) AS VENDEDOR,
      COUNT(DISTINCT C.NUMPED) AS QTPEDIDOS,
      SUM((I.QT * I.PVENDA) + NVL(I.VLOUTRASDESP, 0) + NVL(I.VLFRETE, 0)) AS VLVENDA
    FROM PCPEDC C
    JOIN PCPEDI I
      ON I.NUMPED = C.NUMPED
    LEFT JOIN PCUSUARI U
      ON U.CODUSUR = C.CODUSUR
    WHERE TRUNC(C.DATA) = TRUNC(SYSDATE)
      AND C.CODUSUR = :codusur
      AND C.DTCANCEL IS NULL
      AND C.CONDVENDA IN (1,2,3,7,9,14,15,17,18,19,98)
    GROUP BY C.CODUSUR
  `,

  vendasMesVendedor: `
    SELECT
      C.CODUSUR,
      MAX(U.NOME) AS VENDEDOR,
      COUNT(DISTINCT C.NUMPED) AS QTPEDIDOS,
      SUM((I.QT * I.PVENDA) + NVL(I.VLOUTRASDESP, 0) + NVL(I.VLFRETE, 0)) AS VLVENDA
    FROM PCPEDC C
    JOIN PCPEDI I
      ON I.NUMPED = C.NUMPED
    LEFT JOIN PCUSUARI U
      ON U.CODUSUR = C.CODUSUR
    WHERE TRUNC(C.DATA) BETWEEN TRUNC(SYSDATE, 'MM') AND TRUNC(SYSDATE)
      AND C.CODUSUR = :codusur
      AND C.DTCANCEL IS NULL
      AND C.CONDVENDA IN (1,2,3,7,9,14,15,17,18,19,98)
    GROUP BY C.CODUSUR
  `,

  inadimplenciaPorUsuario: `
    SELECT
      F.CODCLI,
      F.CLIENTE,
      F.CODUSUR,
      F.NOMEVENDEDOR,
      SUM(F.VALOR_ABERTO) AS VALOR_ABERTO,
      MAX(F.DIAS_ATRASO) AS MAIOR_ATRASO
    FROM VW_BOT_INADIMPLENCIA F
    WHERE F.CODUSUR = :codusur
    GROUP BY F.CODCLI, F.CLIENTE, F.CODUSUR, F.NOMEVENDEDOR
    ORDER BY VALOR_ABERTO DESC
  `
};

module.exports = ORACLE_SQL;