const ORACLE_PRODUTO_VENCIMENTO_SQL = {
  listar: `
    SELECT
      EE.CODPROD,
      P.DESCRICAO,
      P.CODFORNEC,
      F.FORNECEDOR,
      SUM(EE.QT) AS QT,
      EE.DTVAL,
      TRUNC(EE.DTVAL) - TRUNC(SYSDATE) AS DIAS_PARA_VENCER,
      CASE
        WHEN TRUNC(EE.DTVAL) < TRUNC(SYSDATE) THEN 'VENCIDO'
        WHEN TRUNC(EE.DTVAL) = TRUNC(SYSDATE) THEN 'VENCE HOJE'
        WHEN TRUNC(EE.DTVAL) BETWEEN TRUNC(SYSDATE) + 1 AND TRUNC(SYSDATE) + 30 THEN 'VENCE EM ATÉ 30 DIAS'
        WHEN TRUNC(EE.DTVAL) BETWEEN TRUNC(SYSDATE) + 31 AND TRUNC(SYSDATE) + 60 THEN 'VENCE EM ATÉ 60 DIAS'
        WHEN TRUNC(EE.DTVAL) BETWEEN TRUNC(SYSDATE) + 61 AND TRUNC(SYSDATE) + 90 THEN 'VENCE EM ATÉ 90 DIAS'
        ELSE 'FORA DA FAIXA'
      END AS STATUS_VENCIMENTO
    FROM PCESTENDERECO EE
    LEFT JOIN PCENDERECO EN
      ON EN.CODENDERECO = EE.CODENDERECO
    LEFT JOIN PCPRODUT P
      ON P.CODPROD = EE.CODPROD
    LEFT JOIN PCFORNEC F
      ON F.CODFORNEC = P.CODFORNEC
    WHERE EN.CODMOTIVOAVARIA IS NULL
      AND EE.QT > 0
      AND EE.DTVAL IS NOT NULL
      AND TRUNC(EE.DTVAL) <= TRUNC(SYSDATE) + 90
      AND P.ESTOQUEPORDTVALIDADE = 'S'
    GROUP BY
      EE.CODPROD,
      P.DESCRICAO,
      P.CODFORNEC,
      F.FORNECEDOR,
      EE.DTVAL
    ORDER BY EE.DTVAL, EE.CODPROD
  `
};

module.exports = ORACLE_PRODUTO_VENCIMENTO_SQL;